version: '3.8'

services:
  db:
    image: postgres:13.4
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    command:
    - sleep
    - infinity
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: hello_world_dev
      PGPORT: 5432
      PGHOST: db
    ports:
      - 4000:4000
    volumes:
      - .:/app
volumes:
  db-data:
